# builds running ZeroMQ
# ZeroMQ version 4.0.5
# version 0.1

FROM jeffchen/centos7
MAINTAINER Jeff Chen, jeff.yuhui.chen@gmail.com
#ENTRYPOINT

# install zmqProxy add into /opt
ADD ./app/ /opt/

CMD ["/bin/bash"]
